set (PETSC_HAVE_BLASLAPACK YES)
set (PETSC_HAVE_VALGRIND YES)
set (PETSC_HAVE_PTHREAD YES)
set (PETSC_HAVE_SCHED_CPU_SET_T 1)
set (PETSC_HAVE_PTHREAD_BARRIER_T 1)
set (PETSC_HAVE_SYS_SYSCTL_H 1)
set (PETSC_HAVE_MPI YES)
set (PETSC_HAVE_MPI_COMBINER_DUP YES)
set (PETSC_HAVE_MPI_COMM_C2F YES)
set (PETSC_HAVE_MPI_EXSCAN YES)
set (PETSC_HAVE_MPI_COMM_F2C YES)
set (PETSC_HAVE_MPI_FINT YES)
set (PETSC_HAVE_MPI_COMM_SPAWN YES)
set (PETSC_HAVE_MPI_TYPE_GET_ENVELOPE YES)
set (PETSC_HAVE_MPI_REDUCE_SCATTER_BLOCK YES)
set (PETSC_HAVE_MPI_FINALIZED YES)
set (PETSC_HAVE_MPI_COMBINER_CONTIGUOUS YES)
set (PETSC_HAVE_MPI_TYPE_GET_EXTENT YES)
set (PETSC_HAVE_MPI_REDUCE_SCATTER YES)
set (PETSC_HAVE_MPI_REDUCE_LOCAL YES)
set (PETSC_HAVE_MPI_WIN_CREATE YES)
set (PETSC_HAVE_MPI_REPLACE YES)
set (PETSC_HAVE_MPI_TYPE_DUP YES)
set (PETSC_HAVE_MPIIO YES)
set (PETSC_HAVE_MPI_INIT_THREAD YES)
set (PETSC_HAVE_MPI_COMBINER_NAMED YES)
set (PETSC_HAVE_MPI_ALLTOALLW YES)
set (PETSC_HAVE_MPI_IN_PLACE YES)
set (PETSC_HAVE_STRCASECMP YES)
set (PETSC_HAVE_GET_NPROCS YES)
set (PETSC_HAVE_POPEN YES)
set (PETSC_HAVE_SIGSET YES)
set (PETSC_HAVE_GETWD YES)
set (PETSC_HAVE_VSNPRINTF YES)
set (PETSC_HAVE_TIMES YES)
set (PETSC_HAVE_DLSYM YES)
set (PETSC_HAVE_SNPRINTF YES)
set (PETSC_HAVE_GETHOSTBYNAME YES)
set (PETSC_HAVE_GETCWD YES)
set (PETSC_HAVE_DLERROR YES)
set (PETSC_HAVE_FORK YES)
set (PETSC_HAVE_RAND YES)
set (PETSC_HAVE_GETTIMEOFDAY YES)
set (PETSC_HAVE_DLCLOSE YES)
set (PETSC_HAVE_UNAME YES)
set (PETSC_HAVE_GETHOSTNAME YES)
set (PETSC_HAVE_MKSTEMP YES)
set (PETSC_HAVE_SIGACTION YES)
set (PETSC_HAVE_DRAND48 YES)
set (PETSC_HAVE_MEMALIGN YES)
set (PETSC_HAVE_VA_COPY YES)
set (PETSC_HAVE_CLOCK YES)
set (PETSC_HAVE_ACCESS YES)
set (PETSC_HAVE_SIGNAL YES)
set (PETSC_HAVE_USLEEP YES)
set (PETSC_HAVE_GETRUSAGE YES)
set (PETSC_HAVE_VFPRINTF YES)
set (PETSC_HAVE_NANOSLEEP YES)
set (PETSC_HAVE_GETDOMAINNAME YES)
set (PETSC_HAVE_TIME YES)
set (PETSC_HAVE_LSEEK YES)
set (PETSC_HAVE_SOCKET YES)
set (PETSC_HAVE_SYSINFO YES)
set (PETSC_HAVE_READLINK YES)
set (PETSC_HAVE_REALPATH YES)
set (PETSC_HAVE_DLOPEN YES)
set (PETSC_HAVE_MEMMOVE YES)
set (PETSC_SIGNAL_CAST  )
set (PETSC_HAVE_SLEEP YES)
set (PETSC_HAVE_VPRINTF YES)
set (PETSC_HAVE_BZERO YES)
set (PETSC_HAVE_GETPAGESIZE YES)
set (PETSC_USE_SOCKET_VIEWER 1)
set (PETSC_USE_SINGLE_LIBRARY 1)
set (PETSC_USE_INFO YES)
set (PETSC_USE_BACKWARD_LOOP 1)
set (PETSC_USE_MALLOC_COALESCED YES)
set (PETSC_USE_LOG YES)
set (PETSC_USE_CTABLE 1)
set (PETSC_USE_COMPLEX NO)
set (PETSC_USE_REAL_DOUBLE YES)
set (PETSC_CLANGUAGE_C YES)
set (PETSC_HAVE_CXX YES)
set (BUILD_SHARED_LIBS YES)
find_library (PETSC_LAPACK_LIB lapack HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_BLAS_LIB blas HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_M_LIB m HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_MPICHCXX_LIB mpichcxx HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_MPICH_LIB mpich HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_OPA_LIB opa HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_MPL_LIB mpl HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_RT_LIB rt HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_PTHREAD_LIB pthread HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_GCC_S_LIB gcc_s HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
find_library (PETSC_DL_LIB dl HINTS "/store/software/opendihu/dependencies/lapack/install/lib" "/usr/lib/gcc-cross/arm-linux-gnueabi/7" "/usr/lib/arm-linux-gnueabi" "/usr/arm-linux-gnueabi/lib" "/store/software/opendihu/dependencies/mpi/install/lib" )
mark_as_advanced (PETSC_LAPACK_LIB PETSC_BLAS_LIB PETSC_M_LIB PETSC_MPICHCXX_LIB PETSC_MPICH_LIB PETSC_OPA_LIB PETSC_MPL_LIB PETSC_RT_LIB PETSC_PTHREAD_LIB PETSC_GCC_S_LIB PETSC_DL_LIB)
set (PETSC_PACKAGE_LIBS "${PETSC_LAPACK_LIB}" "${PETSC_BLAS_LIB}" "${PETSC_M_LIB}" "${PETSC_MPICHCXX_LIB}" "${PETSC_MPICH_LIB}" "${PETSC_OPA_LIB}" "${PETSC_MPL_LIB}" "${PETSC_RT_LIB}" "${PETSC_PTHREAD_LIB}" "${PETSC_GCC_S_LIB}" "${PETSC_DL_LIB}")
set (PETSC_PACKAGE_INCLUDES "/store/software/opendihu/dependencies/mpi/install/include")
