SET (CMAKE_C_COMPILER /store/software/opendihu/dependencies/mpi/install/bin/mpicc CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_C_FLAGS "   -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fvisibility=hidden -O3 " CACHE STRING "Dummy comment" FORCE)
SET (PETSC_CUDA_HOST_FLAGS ,-Wall,-Wwrite-strings,-Wno-strict-aliasing,-Wno-unknown-pragmas,-fvisibility=hidden,-O3 CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_CXX_COMPILER /store/software/opendihu/dependencies/mpi/install/bin/mpicxx CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_CXX_FLAGS " -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fvisibility=hidden -O3     " CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_AR /usr/bin/arm-linux-gnueabi-ar CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_RANLIB /usr/bin/ranlib CACHE FILEPATH "Dummy comment" FORCE)
